src/lib.rs

This is deliberately in the vein of Command::new, and aims to stop exposing as many details of the getopts implementation to the outside world. This should allow more sophisticated things to be added to the API in the future without breaking existing code, though these patches add no extensions. They are, in essence, almost the minimum necessary to move to a builder API -- removing some of the public accesses is the only "non-essential" change. Ideally I'd like to remove/change Options::add_opt too, as that leaks quite a bit of the internal implementation to the outside world, but am unsure if anyone uses it (rustc doesn't).
In essence, code along the lines of:
let opts = &[
optopt("o", "", "set output file name", "NAME"),
optflag("h", "help", "print this help menu")
];
match …

Move getopts to a builder-style API

---

src/lib.rs

The default preserves the previous behaviour, so most users will not notice
any difference. However, if one sets the parsing stye to StopAtFirstFree,
one gets xarg-ish parsing, which is necessary for tools which have
sub-commands passed to them.

Add ability to set different parsing styles for getopts.

---

src/lib.rs

Broken in the recent nightly (`706be5ba1 2015-02-05 23:14:28 +0000`).

Language changes: Closure annotations (|&mut: ..|) are gone.

---

Cargo.toml

Changes the dependency on the log crate to 0.3 from 0.2. Everything still builds just fine.

Bump log dependency to 0.3.

---

src/lib.rs

Now "--arg=A=B" and "--arg A=B" are equivalent.
Fixes #14.

handle '=' in arguments more nicely

---

src/lib.rs

"-" is as a "free" argument, but when it is seen, StopAtFirstFree mode
is not respected.  This patch changes the parser to correctly handle
this case.

fix handling of "-" argument in StopAtFirstFree mode

---

src/lib.rs

This makes the help output look a bit more like many core Linux
utilities.  It lines up long options in a column, when there are any
short options.  And, it separates the short option from the long option
with a comma.
Before:
```
-s --something   [...]
--long           [...]
```
After:
```
-s, --something  [...]
--long       [...]
```
Fixes #23.

line up long options and separate short and long options with a comma

---

src/lib.rs

The example program has a required input that is not reflected in the usage string.

Make usage string match program in docs example.

---

Cargo.toml
src/lib.rs

:sweet_potato:
(Should Fail be renamed to be more consistent with `std` APIs?)

Implemented Error for Fail.

---

src/lib.rs

Several doc comments did not use a period to end a sentence. Since this was the
minority case, I added the periods. Also, the opt_default method did not use the
enum constructor None, but instead used the word none.
Additionally, a comment in the format_option function had two typos. They are
now fixed.

Fix formatting inconsistencies in documentation.

---

src/lib.rs

Without these assertion messages I was getting a slightly unhelpful.  (Only "slightly" in that I could go read the code and see what the problem was \o/).
```
thread '<main>' panicked at 'assertion failed: len == 1 || len == 0', /Users/sam/.cargo/registry/src/github.com-88ac128001ac3a9a/getopts-0.2.14/src/lib.rs:256
```
With this change it looks more like:
```
thread '<main>' panicked at 'The short_name (first argument) should be a single character, or an empty string for none', /Users/sam/.cargo/registry/src/github.com-88ac128001ac3a9a/getopts-0.2.14/src/lib.rs:256
```
Slightly more helpful I think. Is there any way to highlight which caller is at fault rather than saying, failed at `getopts/src/lib.rs:256`?  I noticed https://github.com/rust-lang/rfcs/pull/466, but it seemed to have …

Add helpful explanation to failed assertions validating arguments

---

src/lib.rs

Basically, this just returns an empty vector instead of panicking when an invalid option is passed

No panicking on invalid option

---

src/lib.rs

This adds a "long options only" mode.  This mode prevents clustering of
short options, and recognizes long options with either a "-" or "--".
To avoid possibly conflicting long and short options, I changed getopts generally to reject single-letter long options.  I thought this was a reasonable restriction; but this could be handled a different way with more work -- if you'd prefer that, let me know.
Fixes #17.

add "long options only" mode

---

src/lib.rs

The enum FailType isn't used, so this patch removes it.

Remove FailType

---

src/lib.rs

Other error messages don't seem to end with periods (e.g., the error message for ENOENT is "No such file or directory (os error 2)"), so remove them from the getopts error messages.

Remove periods from error messages

---

src/lib.rs

Juggling of offsets didn't seem Rusty. Parsing using an iterator allows consuming strings as they're parsed, so they don't need to be cloned.

Parse using peekable iterator

---

README.md

Dont mention the patch release to keep the readme in-sync with the other
nursery docs. Right now the patch release is also outdated.

doc: remove patch release semver from readme

---

src/lib.rs

Currently the usage method does the formatting, and there's no way to change it. This add `usage_with_format` that takes a closure. 
private method `usage_items` returns the iterator of the options directly, `usage_with_format` sits on top it, and `usage` in turn sits on top of that.
```rust
/// Derive a formatted message from a set of options.
pub fn usage(&self, brief: &str) -> String {
self.usage_with_format(|opts|
format!("{}\n\nOptions:\n{}\n", brief, opts.collect::<Vec<String>>().join("\n")))
}
/// Derive a custom formatted message from a set of options. The formatted options provided to
/// a closure as an iterator.
pub fn usage_with_format<'a, F: FnMut(Box<Iterator<Item=String> + 'a>) -> String>(&'a self, mut formatter: F) -> String {
formatter(self.usage_items())
}
```
Addresses …

add: usage_with_format

---

Cargo.toml

0.2.15 does not build with non-lexical lifetimes enabled: https://github.com/rust-lang/rust/issues/47707 but `master` does.

Please publish a new version on crates.io

---

Cargo.toml
src/lib.rs

To reproduce, build on Nightly with `RUSTFLAGS=-Znll`

Fix mutable aliasing uncovered by MIR borrow-checking

---

.travis.yml
README.md

I've used [biflags](https://github.com/rust-lang-nursery/bitflags#rust-version-support) as example for a readme note.
Closes #62

Added note about a minimum version.

---

Cargo.toml
src/lib.rs

I have refactored each_split_within() to follow, hopefully, a simpler logic. The test cases are passing and I have added new test case to test multi-width characters.
Let me know if this PR will be useful for this issue or need modifications.
Thanks,

use unicode-width instead of len() or grapheme cluster #7.

---

src/lib.rs

* more tolerant than opt_default.
* folds str::parse() on the argument and returns Result<T,E>.

implement opt_get() method call on Matches.

---

Cargo.toml
src/lib.rs

Closes #73 
See #73 for a list of changes that are included in this release.

Prepare for 0.2.18 release

---

.gitignore
src/lib.rs
src/tests/mod.rs

I added the `Debug` implementation to the `Matches` struct and associated data types.  I also took the liberty to format the code with rustfmt fix some small clippy lints.  The lint changes shouldn't affect the functionality at all.
Fixes #64

add #[derive(Debug)] to Matches struct; run cargo fmt; fix with clippy

---

src/lib.rs
src/tests/mod.rs

This adds two methods:
- `Matches::opt_positions`
- `Matches::opt_strs_pos`
which give a way to get all the positions in which an argument was specified. This is used to decide which argument should take precedence in a case like https://github.com/rust-lang/rust/issues/32352.

Add methods to `Matches` to support getting the index of an argument

---

Cargo.toml
src/lib.rs

[Diff since the last release](https://github.com/rust-lang-nursery/getopts/compare/v0.2.18...master)
Includes:
- #76 
- #77 
- #79

Prepare for 0.2.19 release

---

src/lib.rs
src/tests/mod.rs

Similar to https://github.com/rust-lang-nursery/getopts/issues/49, this changes the parsing of optional short options to require no space between the option and argument. Now, `-aSomething` parse as an option with argument, and `-a Something` will parse as a present flag with a free non-option.
Note that this only changes _optional_ option arguments (when `hasarg = Maybe`, as in `optflagopt`). Required option arguments (when `hasarg = Yes`, as in `optopt`) still allow a space between the short option and its argument.
This is a breaking change.

Parse optional short options like gnu getopt

---

src/lib.rs

The only time the names vector has more than one `Name` in it is when parsing contiguous short options (`-abc`). We would continue putting `Name`s into the vector until we hit a short option that takes an argument. At that point, we break, so we can process the argument.
So there's no point to reprocess the head of that vector, we already know they don't take arguments. Only the last one matters.

Parse options without names vector

---

src/lib.rs
src/tests/mod.rs

This commit reverts three recent PRs to the `getopts` crate. One of the
main consumers of `getopts` is `rustc`, which isn't allowed to have
breaking changes. In #82, however, a breaking change was landed. It
looks like #83 builds on this change, and while #81 seems unrelated the
diffs were somewhat tangled.

Revert #81, #82, #83

---

Cargo.toml

This commit updates the support necessary for this crate to be built as
a dependency of `getopts` which is a dependency of the `test` crate
which is built in rust-lang/rust. This change will be required to land
rust-lang/rust#63637 where Rust's build system is being tweaked
slightly. This is intended to not have any impact on other users of this
crate and the `Cargo.toml` features here should only be used by Rust's
own build system.

Update support for being built in rust-lang/rust

---

src/lib.rs

Also update the name argument to make it more obvious what the "option name" text part is referring to.
Relates to issue #51.

Update documentation of opt_present() and other functions that might panic

---

src/lib.rs

`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon.
This PR:
- Removes an implementation of `Error::description`
Related PR: https://github.com/rust-lang/rust/pull/66919

Remove deprecated Error::description

---

README.md

Just thinking back to #84, we need to be careful not to change the way arguments are parsed or we could change the behaviour of `rustc`.
At this point, maybe it’s worth just bumping `getopts` to `1.0`?

Add a note about getopts constraints

---

src/lib.rs

The pull request contains two changes (in separate commits) for ticket #44 :
1) Update wording of top level documentation to talk only about methods that add configuration options since creating components by hand is not supported in current code.
2) Add examples for methods that add configuration options (except `opt()`)
For the second change I have considered enhancing the top level example, but felt that it would become bloated and hard to read. Instead I've opted into adding short, basic setup & query examples to each method that adds option into parser configuration instance.
I have also submitted ticket #102 as side result of the implementation - using `std::matches` macro could make examples that showcase `Fail` enum shorter and easier to read. But I did not want to break backward …

Update top level docs and docs of methods that configure into Options

---

src/lib.rs
src/tests/mod.rs

The crate provides support for detecting and ignoring double-dash ("--")
argument passed from command line, but it does not provide any
information about its presence or position to user.
For applications that may want to pass arguments after double-dash to
child process is such indication critical.
Add optional field `args_end` into Matches structure storing position of
first argument after double-dash (if there is any) and method to provide
user access to the data.
When checking for double-dash positin, it is important to make sure that
there actually are some arguments after it. Otherwise the position would
point to non-existent index in `free` list and would require additional
unnecessary checks on user side.

Add support for detecting args after double-dash

---

src/lib.rs

Add format string to panic!() when handling Options parse() result
to avoid compiler warning.

Fix compiler warning in documentation example

---

.github/workflows/main.yml
Cargo.toml

Check the MSRV in CI and document it as an extremely low 1.49 (the oldest version I could test with locally, it's probably actually older than that). This is intended so we can do one final release with `rust-version` documented, then increase it in a follow up to 1.66 which will be needed for `unicode-width` 0.2.

Document and start testing the MSRV

---

.github/workflows/main.yaml
Cargo.toml

Match what is required by `unicode-width` version 0.2.

Update the MSRV to 1.66 and edition to 2021

---

Cargo.toml

This updates the `unicode-width` dependency to v0.2.0.

Bump unicode-width to 0.2.0
